/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.50
 * Generated at: 2021-10-06 03:37:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.loginmember;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class member_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script src=\"script.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function idCheck(id) {\r\n");
      out.write("		frm = document.regFrm;\r\n");
      out.write("		if(id == \"\") {\r\n");
      out.write("			alert(\"아이디를 입력하세요\");\r\n");
      out.write("			frm.id.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		url = \"idCheck.jsp?id=\" + id;\r\n");
      out.write("		window.open(url, \"IDCheck\", \"width=300, height=150\");\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function findAddr() {\r\n");
      out.write("		new daum.Postcode({\r\n");
      out.write("	        oncomplete: function(data) {\r\n");
      out.write("	            var roadAddr = data.roadAddress;  // 도로명 주소\r\n");
      out.write("	            var jibunAddr = data.jibunAddress;   // 지번 주소\r\n");
      out.write("	            var extraAddr = '';\r\n");
      out.write("	            \r\n");
      out.write("	            document.getElementById('postcode').value = data.zonecode;\r\n");
      out.write("	            if(roadAddr != '') {\r\n");
      out.write("	            	if(data.bname != '') {\r\n");
      out.write("	            		extraAddr += data.bname;\r\n");
      out.write("	           		}\r\n");
      out.write("	            	if(data.buildingName != '') {\r\n");
      out.write("	            		extraAddr += (extraAddr != '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("	            	}\r\n");
      out.write("	            	roadAddr += (extraAddr != '' ? ' (' + extraAddr + ')' : '');\r\n");
      out.write("	            	document.getElementById('addr').value = roadAddr;\r\n");
      out.write("	            } else if(jibunAddr != '') {\r\n");
      out.write("	            	document.getElementById('addr').value = jibunAddr;\r\n");
      out.write("	            }\r\n");
      out.write("	            document.getElementById('detailAddr').focus();\r\n");
      out.write("	        }\r\n");
      out.write("	    }).open();\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<table align=\"center\" border=1>\r\n");
      out.write("<form name=\"regFrm\" method =\"post\" action=\"memberProc.jsp\">\r\n");
      out.write("	<tr bgcolor=\"green\">\r\n");
      out.write("		<th colspan=\"3\" align=\"center\"><font color=\"white\"><b>회원가입</b></font></th>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td>아이디</td>\r\n");
      out.write("		<td><input name=\"id\"><input type=\"button\" value=\"ID중복확인\" onClick=\"idCheck(this.form.id.value)\"></td>\r\n");
      out.write("		<td>아이디를 입력해 주세요</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td>패스워드</td>\r\n");
      out.write("		<td><input type=\"password\" name=\"pw\"></td>\r\n");
      out.write("		<td>패스워드를 입력해 주세요</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td>패스워드 확인</td>\r\n");
      out.write("		<td><input type=\"password\" name=\"repw\"></td>\r\n");
      out.write("		<td>패스워드를 한번 더 입력해 주세요</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td>이름</td>\r\n");
      out.write("		<td><input name=\"name\"></td>\r\n");
      out.write("		<td>이름을 입력해 주세요</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td>성별</td>\r\n");
      out.write("		<td>\r\n");
      out.write("			<input type=\"radio\" name=\"gender\" value=\"1\"> 남\r\n");
      out.write("			<input type=\"radio\" name=\"gender\" value=\"2\"> 여\r\n");
      out.write("		</td>\r\n");
      out.write("		<td>성별을 선택해 주세요</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td>생년월일</td>\r\n");
      out.write("		<td><input name=\"birthday\" placeholder=\"ex) 970315\"></td>\r\n");
      out.write("		<td>생년월일을 입력해 주세요</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td>E-mail</td>\r\n");
      out.write("		<td><input name=\"email\">@ \r\n");
      out.write("			<select name=\"emailcom\">\r\n");
      out.write("				<option value=\"naver.com\">naver.com\r\n");
      out.write("				<option value=\"daum.net\">daum.net\r\n");
      out.write("				<option value=\"gmail.com\">gmail.com\r\n");
      out.write("				<option value=\"nate.com\">nate.com\r\n");
      out.write("			</select>\r\n");
      out.write("		</td>\r\n");
      out.write("		<td>이메일을 입력해 주세요</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td>우편번호</td>\r\n");
      out.write("		<td><input name=\"zipcode\" id=\"postcode\" readonly>\r\n");
      out.write("			<input type=\"button\" value=\"우편번호 찾기\" onClick=\"findAddr()\"></td>\r\n");
      out.write("		<td>우편번호를 검색하세요</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td>주소</td>\r\n");
      out.write("		<td><input name=\"address\" id=\"addr\" size=\"60\" readonly><br/>\r\n");
      out.write("			<input name=\"detailAddress\" id=\"detailAddr\" placeholder=\"상세주소 넣기\"></td>\r\n");
      out.write("		<td>상세주소가 있으면 입력해주세요</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td>전화번호</td>\r\n");
      out.write("		<td><input name=\"phone\"></td>\r\n");
      out.write("		<td>전화번호를 입력해 주세요</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td>관심과목</td>\r\n");
      out.write("		<td><input type=\"checkbox\" name=\"subject\" value=\"웹페이지\">웹페이지&nbsp;\r\n");
      out.write("			<input type=\"checkbox\" name=\"subject\" value=\"AI\">AI&nbsp;\r\n");
      out.write("			<input type=\"checkbox\" name=\"subject\" value=\"빅데이터\">빅데이터&nbsp;\r\n");
      out.write("			<input type=\"checkbox\" name=\"subject\" value=\"디자인\">디자인&nbsp;\r\n");
      out.write("			<input type=\"checkbox\" name=\"subject\" value=\"JAVA\">JAVA\r\n");
      out.write("		</td>\r\n");
      out.write("		<td>관심과목을 선택하세요</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td>고향</td>\r\n");
      out.write("		<td>\r\n");
      out.write("			<select name=\"hometown\">\r\n");
      out.write("				<option value=\"0\" selected>선택하세요.\r\n");
      out.write("				<option value=\"서울특별시\">서울특별시\r\n");
      out.write("				<option value=\"경기도\">경기도\r\n");
      out.write("				<option value=\"강원도\">강원도\r\n");
      out.write("				<option value=\"충청도\">충청도\r\n");
      out.write("				<option value=\"전라도\">전라도\r\n");
      out.write("				<option value=\"경상도\">경상도\r\n");
      out.write("				<option value=\"인천광역시\">인천광역시\r\n");
      out.write("				<option value=\"대구광역시\">대구광역시\r\n");
      out.write("				<option value=\"대전광역시\">대전광역시\r\n");
      out.write("				<option value=\"울산광역시\">울산광역시\r\n");
      out.write("				<option value=\"부산광역시\">부산광역시\r\n");
      out.write("				<option value=\"광주광역시\">광주광역시\r\n");
      out.write("			</select>\r\n");
      out.write("		</td>\r\n");
      out.write("		<td>고향을 선택해 주세요</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td colspan=\"3\" align=\"center\">\r\n");
      out.write("			<input type=\"button\" value=\"회원가입\" onClick=\"inputCheck()\">&emsp;\r\n");
      out.write("			<input type=\"reset\" value=\"다시쓰기\">&emsp;\r\n");
      out.write("			<input type=\"button\" value=\"로그인\" onClick=\"javascript:location.href='login.jsp'\">\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
